(add-to-list 'load-path "~/.emacs.d/clemacs/utils/")
(load-file "~/.emacs.d/clemacs/repositories.el")
(mapc 'load-file (file-expand-wildcards "~/.emacs.d/clemacs/packages/*.el"))
(load-file "~/.emacs.d/clemacs/interface.el")
(load-file "~/.emacs.d/clemacs/misc.el")